### ISSUE TITLE
一键登录授权按钮背景图片

### ISSUE THREAD

**Issue by Joulloy** [jpush/jverification-hbuilder-plugin#17]
请问一键登录授权按钮如果使用了背景图片的话，勾选和未勾选条款的状态怎么区分呢？因为没有了透明度的改变。我不知道这是我使用方法有问题还是本身插件就存在这个问题。我的目的是想明确知道按钮可以调用的时机，现在未勾选条款的话按钮也没有点击事件

**Comment by JoshLipan** [comment]
不勾选条款，一键登录按钮无法点击
