### ISSUE TITLE
ios privacyOffsetY这个属性存在问题

### ISSUE THREAD

**Issue by Tron1234** [jpush/jverification-hbuilder-plugin#19]
![image](https://user-images.githubusercontent.com/47961959/114848355-3114a000-9e11-11eb-9f0e-72911233e590.png)
这个属性输入负值无效？隐私条款Y偏移量(注:此属性为与屏幕底部的距离)，如果下面写了
![image](https://user-images.githubusercontent.com/47961959/114847913-c95e5500-9e10-11eb-8976-54626548f344.png)
自定义控件就是与自定义组件距离了不是屏幕底部

1.
![image](https://user-images.githubusercontent.com/47961959/114848113-f874c680-9e10-11eb-95bf-f7a976b8a83f.png)
![image](https://user-images.githubusercontent.com/47961959/114848154-fe6aa780-9e10-11eb-967f-900b5fd411d8.png)
这是设置这个值的时候高度

2.
![image](https://user-images.githubusercontent.com/47961959/114848203-09bdd300-9e11-11eb-863c-b3aebff87174.png)
![image](https://user-images.githubusercontent.com/47961959/114848213-0cb8c380-9e11-11eb-8f77-e9c2cdd56f19.png)
这是设置这个值的时候高度

**Comment by huangshuni** [comment]
该属性已经过期，请使用privacyConstraints。
