### ISSUE TITLE
登录按钮的背景色怎么不能改变

### ISSUE THREAD

**Issue by bagefly** [jpush/jverification-hbuilder-plugin#4]
1.默认的蓝色和设置的导航栏背景色很不协调，官方是怎么考虑的呢？
2.导航栏自定义返回按钮图标不出现
请官方人员能不能修复一下，谢谢
@JoshLipan

**Comment by sherryQwl** [comment]
1、登录按钮的背景色可以修改；
2、图标不出现是不是传值类型不对；
可以参考以下文档，排查问题：https://github.com/jpush/jverification-hbuilder-plugin/blob/master/doc/ANDROID.md
